#!usr/bin/python3

""" Module that factoring as many number as possible into a product of two smaller number."""


from sys import argv


def factorize(num):
    """"print a simple descomposition of an integer > 1"""
    i = 2

    if num < 2:
        return
    print()
    print(num, "<- num-bef")
    while num % i:
        i += 1
    print("{:.0f}={:.0f}*{:.0f}".format(num, num / i, i))
    print(num, "<- num-aft")
    print()

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            num = int(line.split('\n')[0])
            factorize(num)
            line = file.readline()
except:
    pass
